//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PearAdminMvcOA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class AccessoryFile
    {
        public int AccessoryId { get; set; }
        public int FileId { get; set; }
        public string AccessoryName { get; set; }
        public int AccessorySize { get; set; }
        public int AccessoryType { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string AccessoryPath { get; set; }
        [JsonIgnore]
        public virtual FileInfo FileInfo { get; set; }
        [JsonIgnore]
        public virtual FileTypeInfo FileTypeInfo { get; set; }
    }
}
