//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PearAdminMvcOA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepartInfo()
        {
            this.ManualSign = new HashSet<ManualSign>();
        }
    
        public int DepartId { get; set; }
        public string DepartName { get; set; }
        public int PrincipalUser { get; set; }
        public string ConnectTelNo { get; set; }
        public Nullable<long> ConnectMobileTelNo { get; set; }
        public Nullable<long> Faxes { get; set; }
        public int BranchId { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualSign> ManualSign { get; set; }
    }
}
