//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PearAdminMvcOA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Management
    {
        public int ManId { get; set; }
        public string ManRoom { get; set; }
        public string ManTitle { get; set; }
        public string ManComm { get; set; }
        public System.DateTime StateTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreaTime { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
