//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PearAdminMvcOA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualSign
    {
        public int SignId { get; set; }
        public int UserId { get; set; }
        public System.DateTime SignTime { get; set; }
        public int SignDesc { get; set; }
        public string SignText { get; set; }
        public int RoleId { get; set; }
        public int DepartId { get; set; }
    
        public virtual DepartInfo DepartInfo { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual Remarks Remarks { get; set; }
        public virtual RoleInfo RoleInfo { get; set; }
    }
}
