//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PearAdminMvcOA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreContract
    {
        public int PreContractId { get; set; }
        public int ScheduleId { get; set; }
        public int UserId { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
