//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PearAdminMvcOA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ReadCommonMessage
    {
        public int ReadId { get; set; }
        public Nullable<int> MessageId { get; set; }
        public Nullable<int> UserId { get; set; }
        [JsonIgnore]
        public virtual Message Message { get; set; }
        [JsonIgnore]
        public virtual UserInfo UserInfo { get; set; }
    }
}
