//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PearAdminMvcOA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.DepartInfo = new HashSet<DepartInfo>();
            this.LoginLog = new HashSet<LoginLog>();
            this.ManualSign = new HashSet<ManualSign>();
            this.MessageToUser = new HashSet<MessageToUser>();
            this.OperateLog = new HashSet<OperateLog>();
            this.PreContract = new HashSet<PreContract>();
            this.ReadCommonMessage = new HashSet<ReadCommonMessage>();
        }
    
        public int UserId { get; set; }
        public string WordId { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public int DepartId { get; set; }
        public int Gender { get; set; }
        public int RoleId { get; set; }
        public int UserState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartInfo> DepartInfo { get; set; }
        public virtual DepartInfo DepartInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginLog> LoginLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualSign> ManualSign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageToUser> MessageToUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperateLog> OperateLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreContract> PreContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadCommonMessage> ReadCommonMessage { get; set; }
        public virtual UserState UserState1 { get; set; }
    }
}
