//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PearAdminMvcOA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTime
    {
        public int WorkTimeId { get; set; }
        public string WordName { get; set; }
        public System.DateTime OnDutyTime { get; set; }
        public System.DateTime OffDutyTime { get; set; }
    }
}
